using UnrealSharp;
using Object = UnrealSharp.UEObject;
using SDK.Script.EngineSDK;
namespace SDK.Script.CgSDKSDK
{
    public class CgSDKBlueprint : BlueprintFunctionLibrary
    {
        public CgSDKBlueprint(ulong addr) : base(addr) { }
        public bool ShowProgressBar(Object progressBarName) { return Invoke<bool>(nameof(ShowProgressBar), progressBarName); }
        public bool SetStateWithKey(Object StateName, byte Key) { return Invoke<bool>(nameof(SetStateWithKey), StateName, Key); }
        public bool SetState(Object StateName) { return Invoke<bool>(nameof(SetState), StateName); }
        public bool SetProgressBarValue(Object progressBarName, int Value) { return Invoke<bool>(nameof(SetProgressBarValue), progressBarName, Value); }
        public bool SetGame(Object gameName) { return Invoke<bool>(nameof(SetGame), gameName); }
        public bool SetEventWithKey(Object EventName, byte Key) { return Invoke<bool>(nameof(SetEventWithKey), EventName, Key); }
        public bool SetEvent(Object EventName) { return Invoke<bool>(nameof(SetEvent), EventName); }
        public bool RequestControl() { return Invoke<bool>(nameof(RequestControl)); }
        public bool ReleaseControl() { return Invoke<bool>(nameof(ReleaseControl)); }
        public void PerformProtocolHandshake() { Invoke(nameof(PerformProtocolHandshake)); }
        public bool HideProgressBar(Object progressBarName) { return Invoke<bool>(nameof(HideProgressBar), progressBarName); }
        public bool ClearStateWithKey(Object StateName, byte Key) { return Invoke<bool>(nameof(ClearStateWithKey), StateName, Key); }
        public bool ClearState(Object StateName) { return Invoke<bool>(nameof(ClearState), StateName); }
        public bool ClearAllStates() { return Invoke<bool>(nameof(ClearAllStates)); }
        public bool ClearAllEvents() { return Invoke<bool>(nameof(ClearAllEvents)); }
    }
    public enum FCgSdkLedId : int
    {
        Invalid = 0,
        K_Escape = 1,
        K_F1 = 2,
        K_F2 = 3,
        K_F3 = 4,
        K_F4 = 5,
        K_F5 = 6,
        K_F6 = 7,
        K_F7 = 8,
        K_F8 = 9,
        K_F9 = 10,
        K_F10 = 11,
        K_F11 = 12,
        K_GraveAccentAndTilde = 13,
        K_2 = 14,
        K_3 = 15,
        K_4 = 16,
        K_5 = 17,
        K_6 = 18,
        K_7 = 19,
        K_8 = 20,
        K_9 = 21,
        K_10 = 22,
        K_1 = 23,
        K_MinusAndUnderscore = 24,
        K_Tab = 25,
        K_Q = 26,
        K_W = 27,
        K_E = 28,
        K_R = 29,
        K_T = 30,
        K_Y = 31,
        K_U = 32,
        K_I = 33,
        K_O = 34,
        K_P = 35,
        K_BracketLeft = 36,
        K_CapsLock = 37,
        K_A = 38,
        K_S = 39,
        K_D = 40,
        K_F = 41,
        K_G = 42,
        K_H = 43,
        K_J = 44,
        K_K = 45,
        K_L = 46,
        K_SemicolonAndColon = 47,
        K_ApostropheAndDoubleQuote = 48,
        K_LeftShift = 49,
        K_NonUsBackslash = 50,
        K_Z = 51,
        K_X = 52,
        K_C = 53,
        K_V = 54,
        K_B = 55,
        K_N = 56,
        K_M = 57,
        K_CommaAndLessThan = 58,
        K_PeriodAndBiggerThan = 59,
        K_SlashAndQuestionMark = 60,
        K_LeftCtrl = 61,
        K_LeftGui = 62,
        K_LeftAlt = 63,
        K_Lang2 = 64,
        K_Space = 65,
        K_Lang1 = 66,
        K_International2 = 67,
        K_RightAlt = 68,
        K_RightGui = 69,
        K_Application = 70,
        K_LedProgramming = 71,
        K_Brightness = 72,
        K_F12 = 73,
        K_PrintScreen = 74,
        K_ScrollLock = 75,
        K_PauseBreak = 76,
        K_Insert = 77,
        K_Home = 78,
        K_PageUp = 79,
        K_BracketRight = 80,
        K_Backslash = 81,
        K_NonUsTilde = 82,
        K_Enter = 83,
        K_International1 = 84,
        K_EqualsAndPlus = 85,
        K_International3 = 86,
        K_Backspace = 87,
        K_Delete = 88,
        K_End = 89,
        K_PageDown = 90,
        K_RightShift = 91,
        K_RightCtrl = 92,
        K_UpArrow = 93,
        K_LeftArrow = 94,
        K_DownArrow = 95,
        K_RightArrow = 96,
        K_WinLock = 97,
        K_Mute = 98,
        K_Stop = 99,
        K_ScanPreviousTrack = 100,
        K_PlayPause = 101,
        K_ScanNextTrack = 102,
        K_NumLock = 103,
        K_KeypadSlash = 104,
        K_KeypadAsterisk = 105,
        K_KeypadMinus = 106,
        K_KeypadPlus = 107,
        K_KeypadEnter = 108,
        K_Keypad7 = 109,
        K_Keypad8 = 110,
        K_Keypad9 = 111,
        K_KeypadComma = 112,
        K_Keypad4 = 113,
        K_Keypad5 = 114,
        K_Keypad6 = 115,
        K_Keypad1 = 116,
        K_Keypad2 = 117,
        K_Keypad3 = 118,
        K_Keypad0 = 119,
        K_KeypadPeriodAndDelete = 120,
        K_G1 = 121,
        K_G2 = 122,
        K_G3 = 123,
        K_G4 = 124,
        K_G5 = 125,
        K_G6 = 126,
        K_G7 = 127,
        K_G8 = 128,
        K_G9 = 129,
        K_G10 = 130,
        K_VolumeUp = 131,
        K_VolumeDown = 132,
        K_MR = 133,
        K_M1 = 134,
        K_M2 = 135,
        K_M3 = 136,
        K_G11 = 137,
        K_G12 = 138,
        K_G13 = 139,
        K_G14 = 140,
        K_G15 = 141,
        K_G16 = 142,
        K_G17 = 143,
        K_G18 = 144,
        K_International5 = 145,
        K_International4 = 146,
        K_Fn = 147,
        M_2 = 148,
        M_3 = 149,
        M_4 = 150,
        M_5 = 151,
        H_LeftLogo = 152,
        H_RightLogo = 153,
        K_Logo = 154,
        MM_Zone1 = 155,
        MM_Zone2 = 156,
        MM_Zone3 = 157,
        MM_Zone4 = 158,
        MM_Zone5 = 159,
        MM_Zone6 = 160,
        MM_Zone7 = 161,
        MM_Zone8 = 162,
        MM_Zone9 = 163,
        MM_Zone10 = 164,
        MM_Zone11 = 165,
        MM_Zone12 = 166,
        MM_Zone13 = 167,
        MM_Zone14 = 168,
        MM_Zone15 = 169,
        KLP_Zone1 = 170,
        KLP_Zone2 = 171,
        KLP_Zone3 = 172,
        KLP_Zone4 = 173,
        KLP_Zone5 = 174,
        KLP_Zone6 = 175,
        KLP_Zone7 = 176,
        KLP_Zone8 = 177,
        KLP_Zone9 = 178,
        KLP_Zone10 = 179,
        KLP_Zone11 = 180,
        KLP_Zone12 = 181,
        KLP_Zone13 = 182,
        KLP_Zone14 = 183,
        KLP_Zone15 = 184,
        KLP_Zone16 = 185,
        KLP_Zone17 = 186,
        KLP_Zone18 = 187,
        KLP_Zone19 = 188,
        M_6 = 189,
        M_7 = 190,
        HSS_Zone1 = 191,
        HSS_Zone2 = 192,
        HSS_Zone3 = 193,
        HSS_Zone4 = 194,
        HSS_Zone5 = 195,
        HSS_Zone6 = 196,
        HSS_Zone7 = 197,
        HSS_Zone8 = 198,
        HSS_Zone9 = 199,
        FCgSdkLedId_MAX = 200,
    }
}
